Feature: Check Demo Borland - GMO website

Scenario: Check end to end flow of Demo Borland
    Given I open the url "http://demo.borland.com/gmopost/"
    When I click on the element "input[name=bSubmit]"
    And I set "10" to the inputfield "input[name=QTY_TENTS]"
    And I set "10" to the inputfield "input[name=QTY_BOOTS]"
    And I click on the button "input[type=submit]"
    Then I expect that the title is "Place Order"
    When I click on the button "input[type=submit]"
    Then I expect that the title is "Billing Information"
    When I set "Dhiresh Mundada" to the inputfield "input[name=billName]"
    And I set "Kalyani Nagar" to the inputfield "input[name=billAddress]"
    And I set "Pune" to the inputfield "input[name=billCity]"
    And I set "Maharashtra" to the inputfield "input[name=billState]"
    And I set "37211" to the inputfield "input[name=billZipCode]"
    And I set "9999999999" to the inputfield "input[name=billPhone]"
    And I set "test@gmail.com" to the inputfield "input[name=billEmail]"
    And I set "411122223333444" to the inputfield "input[name=CardNumber]"
    And I set "02/20" to the inputfield "input[name=CardDate]"
    And I click on the button "input[name=shipSameAsBill]"
    And I click on the button "input[name=bSubmit]"
    Then I expect that the title is "OnLine Store Receipt"
    When I click on the button "input[name=bSubmit]"
    Then I expect that the title is "Welcome to Green Mountain Outpost"

Scenario: Verify invalid ZipCode Alert Message
	Given I open the url "http://demo.borland.com/gmopost/"
    When I click on the element "input[name=bSubmit]"
    And I set "10" to the inputfield "input[name=QTY_TENTS]"
    And I set "10" to the inputfield "input[name=QTY_BOOTS]"
    And I click on the button "input[type=submit]"
    Then I expect that the title is "Place Order"
    When I click on the button "input[type=submit]"
    Then I expect that the title is "Billing Information"
    When I set "Dhiresh Mundada" to the inputfield "input[name=billName]"
    And I set "Kalyani Nagar" to the inputfield "input[name=billAddress]"
    And I set "Pune" to the inputfield "input[name=billCity]"
    And I set "Maharashtra" to the inputfield "input[name=billState]"
    And I set "411037" to the inputfield "input[name=billZipCode]"
    And I set "9999999999" to the inputfield "input[name=billPhone]"
    And I set "test@gmail.com" to the inputfield "input[name=billEmail]"
    And I set "411122223333444" to the inputfield "input[name=CardNumber]"
    And I set "02/20" to the inputfield "input[name=CardDate]"
    And I click on the button "input[name=shipSameAsBill]"
    And I click on the button "input[name=bSubmit]"
    Then I expect that a alertbox is opened
    Then I expect that a alertbox contains the text "Please enter a valid zip code"
